name: Build Bizmatch-API
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
jobs:
  # Build's job
  build:
    name: Build the application
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
     # Checkout code
     - uses: actions/checkout@v2
     # Setup Java
     - uses: actions/setup-java@v2
       with:
         distribution: 'adopt' # See 'Supported distributions' for available options
         java-version: '11'
         cache: 'maven'
     # Build Spring boot
     - name: Build the project
       run: mvn clean install -DskipTests
  # Run automated test
  test:
    name: Run automated test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Checkout code
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'maven'
      - name: Run test
        run: mvn test
      - name: Allure report
        uses: nouhouari/action-allure-report@v0.2.0
      - name: Deploy report to gitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Build directory to deploy
          build_dir: allure-report
          verbose: true  
