name: Build Bizmatch-API
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
jobs:
  # Build's job
  build:
    name: Build the application
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
     # Checkout code
     - uses: actions/checkout@v2
     # Setup Java
     - uses: actions/setup-java@v2
       with:
         distribution: 'adopt' # See 'Supported distributions' for available options
         java-version: '11'
         cache: 'maven'
     # Build Spring boot
     - name: Build the project
       run: mvn clean install -DskipTests
  # Run automated test
  test:
    name: Run automated test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Checkout code
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'maven'
      - name: Run test
        run: mvn test
      - name: Allure report
        # You may pin to the exact commit or the version.
        # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
        uses: afiore/action-allure-report@v0.1.0
